# version: 1.0.0

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000
scan_timeout = 10
continuation_prompt = "[‚ñ∏‚ñπ ](dimmed white)"

format = """
($nix_shell$container$fill$git_metrics\n)\
$cmd_duration\
$hostname\
$localip\
$shlvl\
$os\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$typst\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$bun\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$battery"""

[os]
format = "[$symbol](bold fg:#7aa2f7)"
style = "bold fg:#7aa2f7"
disabled = false

[os.symbols]
Macos = "Óúë "
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Û∞†≥ "
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Manjaro = "Û±òä "
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "Û∞î∂ "
Amazon = "Û∞∏è "
Android = "Û∞Ä≤ "
Arch = "Û∞£á"
Artix = "Û∞£á"
CentOS = "Û±Ñö "
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[‚ùØ](bold italic bright-yellow)"
error_symbol = "[‚úó](bold italic red)"
vimcmd_symbol = "[‚ùÆ](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "‚óå"
vimcmd_replace_symbol = "‚ñ°"
vimcmd_visual_symbol = "Û∞àà"

[shell]
disabled = false
bash_indicator = "Óù†"
zsh_indicator = "Ôíâ"
unknown_indicator = "Û∞û∑ "
style = "bold italic blue"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[env_var.CLAUDE_CODE_ENTRYPOINT]
variable = "CLAUDE_CODE_ENTRYPOINT"
format = "[ ](bold italic bright-cyan)"
style = "bold italic bright-cyan"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "Û∞ãÑ "
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[Û∞ÄÑ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = ""
truncation_length = 2
truncation_symbol = "ÔÅî "
read_only = " Û∞åæ"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [Û∞ò¨](bold bright-blue)'

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = " "
"Music" = "Û∞ùö "
"Pictures" = " "
"Developer" = "Û∞≤ã "

[cmd_duration]
format = "[Û±¶ü $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[Û∞úé](blue italic)"

[localip]
ssh_only = true
format = " Û∞©ü[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = '[[ Û∞•î $time ]($style)]($style)'
time_format = "%I:%M %p"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "Û∞Åπ"
charging_symbol = "[Û∞ÇÑ](italic bold green)"
discharging_symbol = "Û∞ÇÉ"
unknown_symbol = "Û∞Çë"
empty_symbol = "Û∞Çé"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[kubernetes]
disabled = false
format = ' [$symbol$context‚é™$namespace](bold purple)'
symbol = "‚ò∏ "

[kubernetes.context_aliases]
"prod-cluster" = "üî¥ prod"
"dev-cluster" = "üü¢ dev"
"staging-cluster" = "üü° stage"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "Û∞ò¨ "
style = "italic bright-blue"
truncation_symbol = "‚Ä¶"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([‚é™$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed‚é•]($style))"
conflicted = "[Û∞ûá](italic bright-magenta)"
ahead = "[‚á°${count}](italic green)"
behind = "[‚á£${count}](italic red)"
diverged = "[‚áï‚á°${ahead_count}‚á£${behind_count}](italic bright-magenta)"
untracked = "[?](italic bright-yellow)"
stashed = "[Û∞ú¶](italic white)"
modified = "[!](italic yellow)"
staged = "[+${count}](italic bright-cyan)"
renamed = "[Û∞Åï](italic bright-blue)"
deleted = "[‚úò](italic red)"

[git_state]
format = "[$state]($style) "
style = "italic dimmed yellow"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"

[deno]
format = " [deno](italic) [ü¶ï $version](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "Û∞¢± "
style = "bold bright-yellow"

[nodejs]
format = " [node](italic) [Û∞éô ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = [
  "package.json",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
]
detect_folders = ["node_modules"]
detect_extensions = ["js", "mjs", "cjs", "ts"]

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "Û∞å† "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = "Û∞¥≠ "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "Û±òó "
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "Û∞èó "
style = "dimmed yellow italic bold"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = "Û∞õ• "
style = "bold bright-red"
version_format = "${raw}"

[bun]
format = " [bun](italic) [${symbol}${version}]($style)"
symbol = "Û∞≥Æ "
style = "bold yellow"
version_format = "${raw}"

[typst]
format = " [ts](italic) [${symbol}${version}]($style)"
symbol = "Û∞õ¶ "
style = "bold blue"
version_format = "${raw}"
detect_extensions = ["ts", "tsx", "mts", "cts"]
detect_files = ["tsconfig.json"]

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = "Û∞∏è "

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style)'
symbol = "‚òÅÔ∏è"
style = "bold blue"

[buf]
symbol = "Û∞õ¶ "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = "Û∞ô± "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = "Û∞î∂ "
format = " conda [$symbol$environment]($style)"

[dart]
symbol = "Û∞ò® "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = "Û∞°® "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = "Û∞¥π "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = "Û∞ª´ "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = "Û∞üì "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = "Û∞≤í "
format = " hs [$symbol($version )]($style)"

[java]
symbol = "Û∞¨∑ "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = "Û∞£ê "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "Û∞çõ "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "Û∞Ü• "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = 'Û±ÑÖ'
format = '[$symbol nix‚é™$state‚é™]($style) [$name](italic dimmed white)'
impure_msg = '[‚åΩ](bold dimmed red)'
pure_msg = '[‚åæ](bold dimmed green)'
unknown_msg = '[‚óå](bold dimmed yellow)'

[spack]
symbol = "‚óá "
format = " spack [$symbol$environment]($style)"

